// Code generated by goyacc -o src/parser/spanner.go src/parser/spanner.go.y. DO NOT EDIT.
//line src/parser/spanner.go.y:2
package parser

import __yyfmt__ "fmt"

//line src/parser/spanner.go.y:2
//line src/parser/spanner.go.y:5
type yySymType struct {
	yys       int
	empty     struct{}
	bytes     []byte
	str       string
	strs      []string
	col       Column
	cols      []Column
	LastToken int
}

const PRIMARY = 57346
const KEY = 57347
const ASC = 57348
const DESC = 57349
const INTERLEAVE = 57350
const IN = 57351
const PARENT = 57352
const ARRAY = 57353
const OPTIONS = 57354
const NOT = 57355
const NULL = 57356
const ON = 57357
const DELETE = 57358
const CASCADE = 57359
const NO = 57360
const ACTION = 57361
const MAX = 57362
const true = 57363
const null = 57364
const allow_commit_timestamp = 57365
const CREATE = 57366
const ALTER = 57367
const DROP = 57368
const DATABASE = 57369
const TABLE = 57370
const INDEX = 57371
const BOOL = 57372
const INT64 = 57373
const FLOAT64 = 57374
const STRING = 57375
const BYTES = 57376
const DATE = 57377
const TIMESTAMP = 57378
const database_id = 57379
const table_name = 57380
const column_name = 57381
const index_name = 57382
const decimal_value = 57383
const hex_value = 57384

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"PRIMARY",
	"KEY",
	"ASC",
	"DESC",
	"INTERLEAVE",
	"IN",
	"PARENT",
	"ARRAY",
	"OPTIONS",
	"NOT",
	"NULL",
	"ON",
	"DELETE",
	"CASCADE",
	"NO",
	"ACTION",
	"MAX",
	"true",
	"null",
	"allow_commit_timestamp",
	"'('",
	"','",
	"')'",
	"';'",
	"CREATE",
	"ALTER",
	"DROP",
	"DATABASE",
	"TABLE",
	"INDEX",
	"BOOL",
	"INT64",
	"FLOAT64",
	"STRING",
	"BYTES",
	"DATE",
	"TIMESTAMP",
	"database_id",
	"table_name",
	"column_name",
	"index_name",
	"decimal_value",
	"hex_value",
	"'<'",
	"'>'",
	"'='",
}
var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 85

var yyAct = [...]int{

	58, 67, 55, 45, 35, 59, 14, 27, 20, 21,
	22, 23, 24, 25, 26, 61, 18, 10, 9, 43,
	7, 8, 4, 63, 62, 52, 6, 5, 46, 47,
	20, 21, 22, 23, 24, 25, 26, 75, 74, 54,
	53, 15, 16, 51, 34, 33, 11, 71, 72, 78,
	60, 12, 49, 73, 48, 76, 77, 69, 42, 32,
	41, 56, 50, 38, 70, 65, 66, 39, 30, 29,
	68, 37, 64, 40, 31, 36, 3, 2, 1, 57,
	28, 44, 19, 17, 13,
}
var yyPact = [...]int{

	-6, -1000, 0, -1, -11, -1000, -1000, -23, -25, -1000,
	22, -37, 15, 17, -4, 65, -37, 46, -1000, -1000,
	-1000, -1000, -1000, 21, 20, -1000, -1000, -43, 55, 62,
	-1000, 48, 44, -17, -17, -26, -1000, -1000, 53, 19,
	-1000, 1, -1000, 14, -1000, -1000, -1000, -1000, 13, -46,
	51, -38, 27, -1000, -1000, -1000, -27, -2, -1000, 59,
	-48, 42, -1000, -38, -1000, -1000, -1000, 26, -1000, 37,
	-1000, 12, 11, 38, -1000, -1000, -1000, 30, -1000,
}
var yyPgo = [...]int{

	0, 84, 51, 83, 16, 82, 19, 81, 80, 0,
	79, 78, 77, 76, 75, 74, 73, 72, 71, 70,
}
var yyR1 = [...]int{

	0, 11, 11, 12, 13, 2, 2, 2, 1, 8,
	10, 10, 9, 17, 17, 17, 14, 14, 18, 3,
	3, 4, 4, 4, 4, 4, 4, 4, 6, 6,
	5, 16, 16, 16, 15, 15, 19, 19, 19, 7,
	7,
}
var yyR2 = [...]int{

	0, 2, 2, 3, 8, 0, 1, 3, 4, 5,
	1, 3, 2, 0, 1, 1, 0, 1, 5, 1,
	1, 1, 1, 1, 4, 4, 1, 1, 1, 1,
	4, 0, 6, 6, 0, 2, 0, 3, 4, 1,
	1,
}
var yyChk = [...]int{

	-1000, -11, -12, -13, 28, 27, 27, 31, 32, 41,
	42, 24, -2, -1, 43, 26, 25, -3, -4, -5,
	34, 35, 36, 37, 38, 39, 40, 11, -8, 4,
	-2, -15, 13, 24, 24, 47, -14, -18, 8, 5,
	-16, 12, 14, -6, -7, 20, 45, 46, -6, -4,
	9, 24, 24, 26, 26, 48, 10, -10, -9, 43,
	23, 42, 26, 25, -17, 6, 7, 49, -19, 15,
	-9, 21, 22, 16, 26, 26, 17, 18, 19,
}
var yyDef = [...]int{

	0, -2, 0, 0, 0, 1, 2, 0, 0, 3,
	0, 5, 0, 6, 0, 0, 5, 34, 19, 20,
	21, 22, 23, 0, 0, 26, 27, 0, 16, 0,
	7, 31, 0, 0, 0, 0, 4, 17, 0, 0,
	8, 0, 35, 0, 28, 29, 39, 40, 0, 0,
	0, 0, 0, 24, 25, 30, 0, 0, 10, 13,
	0, 36, 9, 0, 12, 14, 15, 0, 18, 0,
	11, 0, 0, 0, 32, 33, 37, 0, 38,
}
var yyTok1 = [...]int{

	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	24, 26, 3, 3, 25, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 27,
	47, 49, 48,
}
var yyTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 28, 29, 30, 31, 32, 33, 34, 35,
	36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
	46,
}
var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 3:
		yyDollar = yyS[yypt-3 : yypt+1]
		//line src/parser/spanner.go.y:53
		{
			SetCreateDatabaseStatement(yylex, yyDollar[1].str, yyDollar[2].str, yyDollar[3].str)
		}
	case 4:
		yyDollar = yyS[yypt-8 : yypt+1]
		//line src/parser/spanner.go.y:59
		{
			SetCreateTableStatement(yylex, yyDollar[1].str, yyDollar[2].str, yyDollar[3].str, yyDollar[5].cols, yyDollar[7].strs)
		}
	case 5:
		yyDollar = yyS[yypt-0 : yypt+1]
		//line src/parser/spanner.go.y:65
		{
			yyVAL.cols = make([]Column, 0, 0)
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line src/parser/spanner.go.y:69
		{
			yyVAL.cols = make([]Column, 0, 1)
			yyVAL.cols = append(yyVAL.cols, yyDollar[1].col)
		}
	case 7:
		yyDollar = yyS[yypt-3 : yypt+1]
		//line src/parser/spanner.go.y:74
		{
			yyVAL.cols = append(yyDollar[3].cols, yyDollar[1].col)
		}
	case 8:
		yyDollar = yyS[yypt-4 : yypt+1]
		//line src/parser/spanner.go.y:80
		{
			yyVAL.col = Column{Name: yyDollar[1].str, Type: yyDollar[2].str}
		}
	case 9:
		yyDollar = yyS[yypt-5 : yypt+1]
		//line src/parser/spanner.go.y:86
		{
			yyVAL.strs = yyDollar[4].strs
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line src/parser/spanner.go.y:92
		{
			yyVAL.strs = make([]string, 0, 1)
			yyVAL.strs = append(yyVAL.strs, yyDollar[1].str)
		}
	case 11:
		yyDollar = yyS[yypt-3 : yypt+1]
		//line src/parser/spanner.go.y:97
		{
			yyVAL.strs = append(yyDollar[1].strs, yyDollar[3].str)
		}
	case 12:
		yyDollar = yyS[yypt-2 : yypt+1]
		//line src/parser/spanner.go.y:103
		{
			yyVAL.str = yyDollar[1].str
		}
	case 19:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line src/parser/spanner.go.y:121
		{
			yyVAL.str = yyDollar[1].str
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line src/parser/spanner.go.y:125
		{
			yyVAL.str = yyDollar[1].str
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line src/parser/spanner.go.y:131
		{
			yyVAL.str = yyDollar[1].str
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line src/parser/spanner.go.y:135
		{
			yyVAL.str = yyDollar[1].str
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line src/parser/spanner.go.y:139
		{
			yyVAL.str = yyDollar[1].str
		}
	case 24:
		yyDollar = yyS[yypt-4 : yypt+1]
		//line src/parser/spanner.go.y:143
		{
			yyVAL.str = yyDollar[1].str + "(" + yyDollar[3].str + ")"
		}
	case 25:
		yyDollar = yyS[yypt-4 : yypt+1]
		//line src/parser/spanner.go.y:147
		{
			yyVAL.str = yyDollar[1].str + "(" + yyDollar[3].str + ")"
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line src/parser/spanner.go.y:151
		{
			yyVAL.str = yyDollar[1].str
		}
	case 27:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line src/parser/spanner.go.y:155
		{
			yyVAL.str = yyDollar[1].str
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line src/parser/spanner.go.y:161
		{
			yyVAL.str = yyDollar[1].str
		}
	case 29:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line src/parser/spanner.go.y:165
		{
			yyVAL.str = "2621440"
		}
	case 30:
		yyDollar = yyS[yypt-4 : yypt+1]
		//line src/parser/spanner.go.y:171
		{
			yyVAL.str = yyDollar[1].str + "(" + yyDollar[3].str + ")"
		}
	case 39:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line src/parser/spanner.go.y:219
		{
			yyVAL.str = yyDollar[1].str
		}
	case 40:
		yyDollar = yyS[yypt-1 : yypt+1]
		//line src/parser/spanner.go.y:223
		{
			yyVAL.str = yyDollar[1].str
		}
	}
	goto yystack /* stack new state and value */
}
